#!/bin/bash


START_TIME=$(date +%s)
echo "print $START_TIME Seconds"
sleep 5

END_TIME=$(date +%s)
echo "print $END_TIME Seconds"

Total_Time=$(($END_TIME-$START_TIME))

echo "Total Time taken is : $Total_Time Seconds" 